server.port=8082

spring.application.name=booking-service

spring.datasource.url=jdbc:mysql://localhost:3306/movie_ticketing
spring.datasource.username=movieapp
spring.datasource.password=MovieApp@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never
