apiVersion: v1
kind: Service

metadata:
  name: movie-service
  namespace: movie-ticketing

spec:
  type: ClusterIP

  selector:
    app: movie-service

  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
